// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TE.Data;

#nullable disable

namespace TE.Data.Migrations
{
    [DbContext(typeof(TEContext))]
    [Migration("20250519004224_newone")]
    partial class newone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TE.Core.Domain.Agenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UtilisateurId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Agendas", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Consultation", b =>
                {
                    b.Property<long>("IdConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdConsultation"));

                    b.Property<DateTime>("DateHeureEffectif")
                        .HasColumnType("datetime2");

                    b.Property<long>("MedecinId")
                        .HasColumnType("bigint");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptomes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("consultationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ficheMedicalId")
                        .HasColumnType("bigint");

                    b.Property<long>("rdvId")
                        .HasColumnType("bigint");

                    b.HasKey("IdConsultation");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.HasIndex("consultationId")
                        .IsUnique();

                    b.HasIndex("ficheMedicalId");

                    b.HasIndex("rdvId")
                        .IsUnique();

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.DemandeConsultation", b =>
                {
                    b.Property<long>("idDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idDemande"));

                    b.Property<long>("MedecinId")
                        .HasColumnType("bigint");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dateDemande")
                        .HasColumnType("datetime2");

                    b.Property<string>("demandeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDemande");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("DemandesConsultation", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Diagnostic", b =>
                {
                    b.Property<long>("IdDiagnostic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdDiagnostic"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateDiagnostic")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gravite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommandations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDiagnostic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ficheMedicalId")
                        .HasColumnType("bigint");

                    b.HasKey("IdDiagnostic");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.HasIndex("ficheMedicalId");

                    b.ToTable("Diagnostics", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Examen", b =>
                {
                    b.Property<long>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdExamen"));

                    b.Property<DateTime>("DateExamen")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DiagnosticIdDiagnostic")
                        .HasColumnType("bigint");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LaboId")
                        .HasColumnType("bigint");

                    b.Property<string>("Resultats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutExamen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeExamen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ficheMedicalId")
                        .HasColumnType("bigint");

                    b.Property<long>("medecinId")
                        .HasColumnType("bigint");

                    b.Property<long>("patientId")
                        .HasColumnType("bigint");

                    b.HasKey("IdExamen");

                    b.HasIndex("DiagnosticIdDiagnostic");

                    b.HasIndex("LaboId");

                    b.HasIndex("ficheMedicalId");

                    b.HasIndex("medecinId");

                    b.HasIndex("patientId");

                    b.ToTable("Examens", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.FicheMedical", b =>
                {
                    b.Property<long>("idFiche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idFiche"));

                    b.Property<bool?>("Alcolique")
                        .HasColumnType("bit");

                    b.Property<string>("AllergiesConnus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Fummeur")
                        .HasColumnType("bit");

                    b.Property<float?>("IMC")
                        .HasColumnType("real");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("antecedentsFamiliaux")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("antecedentsMedicaux")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("poids")
                        .HasColumnType("real");

                    b.Property<string>("sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("taille")
                        .HasColumnType("real");

                    b.Property<string>("traitementChroniques")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeSang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFiche");

                    b.ToTable("FichesMedicales", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Medicament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContreIndications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DiagnosticIdDiagnostic")
                        .HasColumnType("bigint");

                    b.Property<int>("DisponibiliteStock")
                        .HasColumnType("int");

                    b.Property<string>("DosageDisponible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffetsSecondaires")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fabricant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormePharmaceutique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interactions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipeActif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Prix")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticIdDiagnostic");

                    b.ToTable("Medicaments", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<long>("DestinataireId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.Ordenance", b =>
                {
                    b.Property<long>("IdOrdonnance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOrdonnance"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarques")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ficheMedicalId")
                        .HasColumnType("bigint");

                    b.Property<long>("medecinId")
                        .HasColumnType("bigint");

                    b.Property<long>("patientId")
                        .HasColumnType("bigint");

                    b.HasKey("IdOrdonnance");

                    b.HasIndex("ficheMedicalId");

                    b.HasIndex("medecinId");

                    b.HasIndex("patientId");

                    b.ToTable("Ordonnances", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.PrescriptionMedicament", b =>
                {
                    b.Property<long>("OrdonnanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicamentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AvantRepas")
                        .HasColumnType("bit");

                    b.Property<string>("Duree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrdenanceIdOrdonnance")
                        .HasColumnType("bigint");

                    b.Property<string>("Posologie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrdonnanceId", "MedicamentId");

                    b.HasIndex("MedicamentId");

                    b.HasIndex("OrdenanceIdOrdonnance");

                    b.ToTable("PrescriptionMedicaments", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.RendezVous", b =>
                {
                    b.Property<long>("idRdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("idRdv"));

                    b.Property<long>("AgendaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedecinId")
                        .HasColumnType("bigint");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("heure")
                        .HasColumnType("time");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRdv");

                    b.HasIndex("AgendaId")
                        .IsUnique();

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("RendezVous", (string)null);
                });

            modelBuilder.Entity("TE.Core.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<long>("phoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TE.Core.Domain.Admin", b =>
                {
                    b.HasBaseType("TE.Core.Domain.User");

                    b.Property<string>("idAdmin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("TE.Core.Domain.Medecin", b =>
                {
                    b.HasBaseType("TE.Core.Domain.User");

                    b.Property<string>("specialite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Medecin");
                });

            modelBuilder.Entity("TE.Core.Domain.Patient", b =>
                {
                    b.HasBaseType("TE.Core.Domain.User");

                    b.Property<long?>("ficheMedicalId")
                        .HasColumnType("bigint");

                    b.HasIndex("ficheMedicalId")
                        .IsUnique()
                        .HasFilter("[ficheMedicalId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("TE.Core.Domain.Agenda", b =>
                {
                    b.HasOne("TE.Core.Domain.User", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("TE.Core.Domain.Consultation", b =>
                {
                    b.HasOne("TE.Core.Domain.Medecin", "medecin")
                        .WithMany("consultationList")
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Patient", "patient")
                        .WithMany("consultationList")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Ordenance", "Ordonnance")
                        .WithOne("Consultation")
                        .HasForeignKey("TE.Core.Domain.Consultation", "consultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.FicheMedical", "ficheMedical")
                        .WithMany("Consultations")
                        .HasForeignKey("ficheMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.RendezVous", "Rdv")
                        .WithOne()
                        .HasForeignKey("TE.Core.Domain.Consultation", "rdvId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordonnance");

                    b.Navigation("Rdv");

                    b.Navigation("ficheMedical");

                    b.Navigation("medecin");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("TE.Core.Domain.DemandeConsultation", b =>
                {
                    b.HasOne("TE.Core.Domain.Medecin", "MedecinSuggeré")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedecinSuggeré");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("TE.Core.Domain.Diagnostic", b =>
                {
                    b.HasOne("TE.Core.Domain.Consultation", "consultation")
                        .WithOne("diagnostic")
                        .HasForeignKey("TE.Core.Domain.Diagnostic", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.FicheMedical", "ficheMedical")
                        .WithMany("diagnostics")
                        .HasForeignKey("ficheMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("consultation");

                    b.Navigation("ficheMedical");
                });

            modelBuilder.Entity("TE.Core.Domain.Examen", b =>
                {
                    b.HasOne("TE.Core.Domain.Diagnostic", null)
                        .WithMany("ExamensAssocies")
                        .HasForeignKey("DiagnosticIdDiagnostic");

                    b.HasOne("TE.Core.Domain.Admin", "Labo")
                        .WithMany()
                        .HasForeignKey("LaboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.FicheMedical", "ficheMedical")
                        .WithMany("examens")
                        .HasForeignKey("ficheMedicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("medecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Labo");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");

                    b.Navigation("ficheMedical");
                });

            modelBuilder.Entity("TE.Core.Domain.Medicament", b =>
                {
                    b.HasOne("TE.Core.Domain.Diagnostic", null)
                        .WithMany("TraitementsRecommandes")
                        .HasForeignKey("DiagnosticIdDiagnostic");
                });

            modelBuilder.Entity("TE.Core.Domain.Notification", b =>
                {
                    b.HasOne("TE.Core.Domain.User", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destinataire");
                });

            modelBuilder.Entity("TE.Core.Domain.Ordenance", b =>
                {
                    b.HasOne("TE.Core.Domain.FicheMedical", "ficheMedical")
                        .WithMany()
                        .HasForeignKey("ficheMedicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("medecinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patient");

                    b.Navigation("ficheMedical");
                });

            modelBuilder.Entity("TE.Core.Domain.PrescriptionMedicament", b =>
                {
                    b.HasOne("TE.Core.Domain.Medicament", "Medicament")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Ordenance", null)
                        .WithMany("ListeMedicaments")
                        .HasForeignKey("OrdenanceIdOrdonnance");

                    b.HasOne("TE.Core.Domain.Ordenance", "Ordonnance")
                        .WithMany("Prescriptions")
                        .HasForeignKey("OrdonnanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicament");

                    b.Navigation("Ordonnance");
                });

            modelBuilder.Entity("TE.Core.Domain.RendezVous", b =>
                {
                    b.HasOne("TE.Core.Domain.Agenda", "Agenda")
                        .WithOne("RendezVous")
                        .HasForeignKey("TE.Core.Domain.RendezVous", "AgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TE.Core.Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TE.Core.Domain.Patient", b =>
                {
                    b.HasOne("TE.Core.Domain.FicheMedical", "ficheMedical")
                        .WithOne("patient")
                        .HasForeignKey("TE.Core.Domain.Patient", "ficheMedicalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ficheMedical");
                });

            modelBuilder.Entity("TE.Core.Domain.Agenda", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("TE.Core.Domain.Consultation", b =>
                {
                    b.Navigation("diagnostic")
                        .IsRequired();
                });

            modelBuilder.Entity("TE.Core.Domain.Diagnostic", b =>
                {
                    b.Navigation("ExamensAssocies");

                    b.Navigation("TraitementsRecommandes");
                });

            modelBuilder.Entity("TE.Core.Domain.FicheMedical", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("diagnostics");

                    b.Navigation("examens");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("TE.Core.Domain.Medicament", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("TE.Core.Domain.Ordenance", b =>
                {
                    b.Navigation("Consultation")
                        .IsRequired();

                    b.Navigation("ListeMedicaments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("TE.Core.Domain.Medecin", b =>
                {
                    b.Navigation("consultationList");
                });

            modelBuilder.Entity("TE.Core.Domain.Patient", b =>
                {
                    b.Navigation("consultationList");
                });
#pragma warning restore 612, 618
        }
    }
}
