<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.2.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.2.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TE.Core.Interfaces\TE.Core.Interfaces.csproj" />
    <ProjectReference Include="..\TE.Data\TE.Data.csproj" />
    <ProjectReference Include="..\TE.Domain\TE.Core.Domain.csproj" />
  </ItemGroup>

</Project>
